/**
 * Toolbar tool plugins. Each plugin describes a parameter form; `generate`
 * returns the OpenSCAD code inserted into the editor and `preview` returns a
 * self-contained snippet compiled for the dialog's live 3D preview.
 *
 * To add a plugin: write a ToolPlugin object and append it to PLUGINS.
 */

export type ParamValue = number | boolean | string;

export interface PluginParam {
  key: string;
  label: string;
  type: "number" | "int" | "bool" | "select";
  default: ParamValue;
  min?: number;
  max?: number;
  step?: number;
  options?: string[];
  help?: string;
}

export interface ToolPlugin {
  id: string;
  name: string;
  blurb: string;
  params: PluginParam[];
  generate(v: Record<string, ParamValue>): string;
  preview(v: Record<string, ParamValue>): string;
}

const n = (v: ParamValue) => Number(v);
const b = (v: ParamValue) => (v ? "true" : "false");

// ---------------------------------------------------------------- gear

const gearBuilder: ToolPlugin = {
  id: "gear",
  name: "Gear builder",
  blurb: "Involute spur gear with optional hub, bore, helix and lightening holes.",
  params: [
    { key: "m", label: "Module (mm/tooth)", type: "number", default: 2, min: 0.5, max: 6, step: 0.25 },
    { key: "z", label: "Teeth", type: "int", default: 20, min: 6, max: 80, step: 1 },
    { key: "pa", label: "Pressure angle", type: "number", default: 20, min: 14, max: 30, step: 0.5 },
    { key: "thickness", label: "Thickness", type: "number", default: 6, min: 1, max: 30, step: 0.5 },
    { key: "bore", label: "Bore Ø", type: "number", default: 6, min: 0, max: 30, step: 0.5 },
    { key: "hub_d", label: "Hub Ø (0 = none)", type: "number", default: 14, min: 0, max: 60, step: 1 },
    { key: "hub_h", label: "Hub extra height", type: "number", default: 4, min: 0, max: 30, step: 0.5 },
    { key: "helix", label: "Helix twist (°)", type: "number", default: 0, min: -45, max: 45, step: 1 },
    { key: "spoke_holes", label: "Lightening holes", type: "int", default: 4, min: 0, max: 12, step: 1 },
  ],
  generate(v) {
    return `// Involute spur gear (generated by the WebSCAD gear builder)
module spur_gear(m = ${n(v.m)}, z = ${n(v.z)}, pa = ${n(v.pa)}, thickness = ${n(v.thickness)},
                 bore = ${n(v.bore)}, hub_d = ${n(v.hub_d)}, hub_h = ${n(v.hub_h)},
                 helix = ${n(v.helix)}, spoke_holes = ${n(v.spoke_holes)}) {
    rp = m * z / 2;           // pitch radius
    rb = rp * cos(pa);        // base circle
    ra = rp + m;              // tip radius
    rr = rp - 1.25 * m;       // root radius
    K = 8;                    // samples per flank

    function ix(t) = rb * (cos(t) + PI / 180 * t * sin(t));
    function iy(t) = rb * (sin(t) - PI / 180 * t * cos(t));
    function irad(t) = sqrt(ix(t) ^ 2 + iy(t) ^ 2);
    function itheta(t) = atan2(iy(t), ix(t));
    function ppt(r, a) = [r * cos(a), r * sin(a)];

    ta = sqrt((ra / rb) ^ 2 - 1) * 180 / PI;
    tp = sqrt((rp / rb) ^ 2 - 1) * 180 / PI;
    thp = itheta(tp);

    function aL(t) = itheta(t) - thp - 90 / z;
    function aR(t) = -(itheta(t) - thp) + 90 / z;

    outline = [for (k = [0 : z - 1]) each concat(
        [ppt(rr, k * 360 / z - 180 / z)],
        [ppt(rr, k * 360 / z + aL(0))],
        [for (i = [0 : K]) ppt(irad(ta * i / K), k * 360 / z + aL(ta * i / K))],
        [for (i = [K : -1 : 0]) ppt(irad(ta * i / K), k * 360 / z + aR(ta * i / K))],
        [ppt(rr, k * 360 / z + aR(0))]
    )];

    ring_r = (rr + max(bore, hub_d) / 2) / 2;          // spoke-hole circle
    hole_r = (rr - max(bore, hub_d) / 2) * 0.22;

    difference() {
        union() {
            linear_extrude(thickness, twist = helix,
                           slices = helix == 0 ? 1 : 16)
                polygon(outline);
            if (hub_d > 0)
                cylinder(h = thickness + hub_h, d = hub_d, $fn = 48);
        }
        if (bore > 0)
            translate([0, 0, -1])
                cylinder(h = thickness + hub_h + 2, d = bore, $fn = 32);
        if (spoke_holes > 0 && hole_r > 0.8)
            for (i = [0 : spoke_holes - 1])
                rotate([0, 0, (i + 0.5) * 360 / spoke_holes])
                    translate([ring_r, 0, -1])
                        cylinder(h = thickness + 2, r = hole_r, $fn = 24);
    }
}

spur_gear();
`;
  },
  preview(v) {
    return this.generate(v);
  },
};

// ------------------------------------------------------------ polar array

const polarArray: ToolPlugin = {
  id: "polar-array",
  name: "Polar array",
  blurb: "Distribute children in a circle (or helix) around the Z axis.",
  params: [
    { key: "count", label: "Count", type: "int", default: 8, min: 2, max: 64, step: 1 },
    { key: "radius", label: "Radius", type: "number", default: 22, min: 0, max: 200, step: 1 },
    { key: "start", label: "Start angle", type: "number", default: 0, min: -360, max: 360, step: 5 },
    { key: "sweep", label: "Sweep (°)", type: "number", default: 360, min: 10, max: 360, step: 5 },
    { key: "pitch", label: "Z pitch per item (helix)", type: "number", default: 0, min: -20, max: 20, step: 0.5 },
    { key: "rotate_items", label: "Rotate items with circle", type: "bool", default: true },
  ],
  generate(v) {
    return `// Polar array (generated by WebSCAD tools) — wraps its children
module polar_array(count = ${n(v.count)}, radius = ${n(v.radius)}, start = ${n(v.start)},
                   sweep = ${n(v.sweep)}, pitch = ${n(v.pitch)}, rotate_items = ${b(v.rotate_items)}) {
    astep = sweep >= 360 ? sweep / count : sweep / max(1, count - 1);
    for (i = [0 : count - 1]) {
        ang = start + i * astep;
        rotate([0, 0, ang])
            translate([radius, 0, i * pitch])
                rotate([0, 0, rotate_items ? 0 : -ang])
                    children();
    }
}

polar_array()
    cylinder(h = 8, r = 3);   // <- replace with your shape
`;
  },
  preview(v) {
    return this.generate(v).replace(
      "cylinder(h = 8, r = 3);   // <- replace with your shape",
      "cube([6, 3, 8]);",
    );
  },
};

// ------------------------------------------------------------- grid array

const gridArray: ToolPlugin = {
  id: "grid-array",
  name: "Grid array",
  blurb: "Distribute children on a rectangular (or 3D) grid.",
  params: [
    { key: "nx", label: "Count X", type: "int", default: 4, min: 1, max: 30, step: 1 },
    { key: "ny", label: "Count Y", type: "int", default: 3, min: 1, max: 30, step: 1 },
    { key: "nz", label: "Count Z", type: "int", default: 1, min: 1, max: 30, step: 1 },
    { key: "dx", label: "Spacing X", type: "number", default: 15, min: 1, max: 100, step: 1 },
    { key: "dy", label: "Spacing Y", type: "number", default: 15, min: 1, max: 100, step: 1 },
    { key: "dz", label: "Spacing Z", type: "number", default: 15, min: 1, max: 100, step: 1 },
    { key: "center", label: "Center on origin", type: "bool", default: true },
  ],
  generate(v) {
    return `// Grid array (generated by WebSCAD tools) — wraps its children
module grid_array(nx = ${n(v.nx)}, ny = ${n(v.ny)}, nz = ${n(v.nz)},
                  dx = ${n(v.dx)}, dy = ${n(v.dy)}, dz = ${n(v.dz)}, center = ${b(v.center)}) {
    offs = center ? [-(nx - 1) * dx / 2, -(ny - 1) * dy / 2, -(nz - 1) * dz / 2]
                  : [0, 0, 0];
    for (i = [0 : nx - 1], j = [0 : ny - 1], k = [0 : nz - 1])
        translate(offs + [i * dx, j * dy, k * dz])
            children();
}

grid_array()
    cylinder(h = 6, r = 4);   // <- replace with your shape
`;
  },
  preview(v) {
    return this.generate(v);
  },
};

// -------------------------------------------------------- surface scatter

const surfaceScatter: ToolPlugin = {
  id: "scatter",
  name: "Surface scatter",
  blurb: "Distribute children over the surface of a sphere, oriented along the surface normal (Fibonacci spiral).",
  params: [
    { key: "count", label: "Count", type: "int", default: 48, min: 3, max: 300, step: 1 },
    { key: "radius", label: "Sphere radius", type: "number", default: 24, min: 2, max: 150, step: 1 },
    { key: "hemisphere", label: "Upper hemisphere only", type: "bool", default: false },
    { key: "align_normal", label: "Orient +Z along normal", type: "bool", default: true },
    { key: "show_host", label: "Show host sphere (%)", type: "bool", default: true },
  ],
  generate(v) {
    return `// Surface scatter (generated by WebSCAD tools) — distributes children
// on a sphere using a Fibonacci spiral; each child's +Z points outward.
module sphere_scatter(count = ${n(v.count)}, radius = ${n(v.radius)},
                      hemisphere = ${b(v.hemisphere)}, align_normal = ${b(v.align_normal)}) {
    ga = 137.50776;                       // golden angle
    for (i = [0 : count - 1]) {
        zu = 1 - (i + 0.5) * (hemisphere ? 1 : 2) / count;   // unit z
        ru = sqrt(1 - zu * zu);
        az = i * ga;
        polar = acos(zu);
        translate(radius * [ru * cos(az), ru * sin(az), zu])
            rotate(align_normal ? [0, polar, az] : [0, 0, 0])
                children();
    }
}

${v.show_host ? `%sphere(${n(v.radius)}, $fn = 48);   // host object (background modifier)\n` : ""}sphere_scatter()
    cylinder(h = 5, r1 = 1.8, r2 = 0, $fn = 16);   // <- replace with your shape
`;
  },
  preview(v) {
    return this.generate(v);
  },
};

// ------------------------------------------------------------ mirror copy

const mirrorCopy: ToolPlugin = {
  id: "mirror-copy",
  name: "Mirror copy",
  blurb: "Keep the original and add a mirrored twin — handy for symmetric parts.",
  params: [
    { key: "axis", label: "Mirror across", type: "select", default: "X", options: ["X", "Y", "Z"] },
  ],
  generate(v) {
    const vec = v.axis === "X" ? "[1, 0, 0]" : v.axis === "Y" ? "[0, 1, 0]" : "[0, 0, 1]";
    return `// Mirror copy (generated by WebSCAD tools) — wraps its children
module mirror_copy(v = ${vec}) {
    children();
    mirror(v) children();
}

mirror_copy()
    translate([12, 4, 0]) cube([8, 5, 10]);   // <- replace with your shape
`;
  },
  preview(v) {
    return this.generate(v);
  },
};

// ----------------------------------------------------------------- align

const alignTool: ToolPlugin = {
  id: "align",
  name: "Align to origin",
  blurb: "Position the bounding box of any shape relative to the origin — align() is a WebSCAD extension (plain OpenSCAD cannot measure children).",
  params: [
    { key: "x", label: "X axis", type: "select", default: "center", options: ["none", "min", "center", "max"] },
    { key: "y", label: "Y axis", type: "select", default: "center", options: ["none", "min", "center", "max"] },
    { key: "z", label: "Z axis", type: "select", default: "min", options: ["none", "min", "center", "max"] },
  ],
  generate(v) {
    const args = (["x", "y", "z"] as const)
      .filter((k) => v[k] !== "none")
      .map((k) => `${k} = "${v[k]}"`)
      .join(", ");
    return `// align() positions its children's bounding box relative to the origin.
// (WebSCAD extension: "min" | "center" | "max" per axis.)
align(${args})
    translate([13, 7, 5]) sphere(8, $fn = 32);   // <- replace with your shape
`;
  },
  preview(v) {
    return (
      this.generate(v) +
      `\ncolor("red") sphere(1.4, $fn = 24);   // origin marker\n%cube([40, 40, 0.4], center = true);  // ground plane\n`
    );
  },
};

export const PLUGINS: ToolPlugin[] = [
  gearBuilder,
  polarArray,
  gridArray,
  surfaceScatter,
  mirrorCopy,
  alignTool,
];

export function findPlugin(id: string): ToolPlugin | null {
  return PLUGINS.find((p) => p.id === id) ?? null;
}
